---
title: "APS Odd Semester 2024 Coding Problem Set-2"
editor_options:
  chunk_output_type: console
output:
  word_document: default
  html_notebook: default
---
---
title: "APS Odd Semester 2024 Coding Problem Set-2"
editor_options:
  chunk_output_type: console
output:
  html_document:
    df_print: paged
  html_notebook: default
  word_document: default
---

```{r}
library(ggplot2)
library(dplyr)
```

```{r}
# Load the house price dataset
hData = read.csv('Data/houseprices.csv', header = TRUE, stringsAsFactors = FALSE, na.strings = c("", "NA", "Not Available", "not available"))
str(hData)
```

```{r}
# Create a New Data column House_Value = area*price_per_sqft which can we used to make buy, rent decision 
hData = hData %>% mutate(House_Value = area*price_per_sqft)
str(hData)
```

```{r}
# create a New Data Column Decision either to buy or rent the house based on the standard house Price-to-Rent Ratio
hData = hData %>% mutate(Decision = ifelse((House_Value / (rent * 12)) < 15, "Rent", "Buy"))
str(hData)
```

```{r}
# Convert 'locality', 'facing' and 'parking' columns to factors
categorical_cols = c('locality', 'facing', 'parking', 'Decision')
hData[categorical_cols] = lapply(hData[categorical_cols], as.factor)
str(hData)
```

```{r}
# Continuous columns
continuous_cols = setdiff(colnames(hData), categorical_cols)
```

```{r}
# Plot percentage of NAs in each column of the data frame
hData_NA = setNames(stack(sapply(hData, function(x){(sum(is.na(x))/length(x))*100}))[2:1], c('Feature','Value'))
p = ggplot(data = hData_NA, aes(x = Feature, y = Value)) +
  geom_bar(stat = 'identity', fill = 'steelblue', width = 0.3) +
  theme(text = element_text(size = 14, face = 'bold'),
  axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5)) +
  xlab('') + ylab('Percentage') +
  ggtitle('Percentage of NAs across all features')
p
```

```{r}
categorical_cols1 = c('facing', 'parking')
# Add NA as a factor level for categorical columns facing and parking only
hData[categorical_cols1] = lapply(hData[categorical_cols1], addNA)
str(hData)
```

```{r}
#see what all locations are present
distinct_values = unique(hData$locality)
print(distinct_values)
```

```{r}
pcustom_colors = c(
  "Attibele" = "darkorange",  # Dark Orange
  "BTM Layout" = "royalblue",        # Royal Blue
  "Electronic City" = "forestgreen",        # Forest Green
  "Indiranagar" = "steelblue",               # Gold
  "Jayanagar" = "purple",   # Rebecca Purple
  "K R Puram " = "deeppink",        # Deep Pink
  "Malleshwaram" = "yellow",     # Medium Sea Green
  "Marathahalli" = "brown",         # Saddle Brown
  "Yalahanka" = "gray"          # Firebrick
)
```

```{r}
p = ggplot(data = hData) +
  geom_bar(aes(x = locality, fill = Decision)) +
  labs(x = "Locality", y = "Count", title = "Decision to buy or rent the House in any Given Locality")
p
# From Here I conclude that price_per_sqft Is not so Important Based the Standard Rules
```

```{r}
# Area based Houses in different loacalities in Banglaore
p = ggplot(data = hData) +
  geom_histogram(aes(x = area, fill = locality), binwidth = 1000) +
  scale_fill_manual(values = pcustom_colors) 
p
```

```{r}
p = ggplot(data = hData) + geom_point(aes(x = area, y = rent, colour = locality)) 
#scale_y_continuous(breaks = seq(10000, max(hData$rent, na.rm = TRUE), by = 10000))
p
```

```{r}
p = ggplot(data = hData) +
  geom_histogram(aes(x = rent, fill = locality), binwidth = 10000) +
  scale_fill_manual(values = pcustom_colors) +
  scale_x_continuous(limits = c(0, 100000), breaks = seq(0, 100000, by = 10000)) +
  labs(x = "Rent", y = "Count", title = "Histogram of Rent by Locality") +
  theme_minimal()
p
```


```{r}
# Boxplot area in all Localities
p_area_facing = ggplot(data = hData) +
  geom_boxplot(aes(x = locality, y = area, fill = locality), outlier.colour = "red") + 
  scale_fill_manual(values = pcustom_colors) +
  labs(x = "Locality", y = "Area", title = "Area by Locality") +
  theme_minimal()

p_area_facing
```

```{r}
# box plot rent by locality
p_area_rent = ggplot(data = hData) +
  geom_boxplot(aes(x = locality, y = rent, fill = locality), outlier.colour = "red") +
  scale_fill_manual(values = pcustom_colors) +
  labs(x = "Locality", y = "Rent", title = "Rent Distribution by Locality") +
  theme_minimal()

# Display the plot
p_area_rent
```


```{r}
# Boxplot area vs rent in all Localities
p_area_facing = ggplot(data = hData) +
  geom_boxplot(aes(x = area, y = rent, fill = locality), outlier.colour = "red") + 
  scale_fill_manual(values = pcustom_colors) +
  labs(x = "Area", y = "Rent", title = "Rent by Area and Locality") +
  theme_minimal()
p_area_facing
```

```{r}
# Create the plot
p_area_facing = ggplot(data = hData) +
  geom_boxplot(aes(x = (facing = 'East'), y = area, fill = locality), outlier.colour = "red") + 
  scale_fill_manual(values = pcustom_colors) +
  labs(x = "Facing", y = "Area", title = "Area by Facing and Locality") +
  theme_minimal()

# Display the plot
p_area_facing
```

```{r}
p_area_rent = ggplot(data = hData) +
  geom_boxplot(aes(x = rent, y = area, fill = locality), outlier.colour = "red") + 
  scale_fill_manual(values = pcustom_colors) +
  labs(x = "Rent", y = "Area", title = "Area by Rent and Locality for all House Facings") +
  facet_wrap(~ facing) +  # Add this line to create separate plots for each facing
  theme_minimal()

# Display the plot
p_area_rent
```

```{r}
hData_EF = hData %>% filter(facing == 'East')

p_area_rent = ggplot(data = hData_EF) +
  geom_boxplot(aes(x = rent, y = area, fill = locality), outlier.colour = "red") + 
  scale_fill_manual(values = pcustom_colors) +
  labs(x = "Rent", y = "Area", title = "Area by Rent and Locality for East facing") +
  facet_wrap(~ facing) +  # Add this line to create separate plots for each facing
  theme_minimal()

# Display the plot
p_area_rent
```

```{r}
hData_WF = hData %>% filter(facing == 'West')

p_area_rent = ggplot(data = hData_WF) +
  geom_boxplot(aes(x = rent, y = area, fill = locality), outlier.colour = "red") + 
  scale_fill_manual(values = pcustom_colors) +
  labs(x = "Rent", y = "Area", title = "Area by Rent and Locality for West facing") +
  facet_wrap(~ facing) +  # Add this line to create separate plots for west facing
  theme_minimal()

# Display the plot
p_area_rent
```

```{r}
hData_NF = hData %>% filter(facing == 'North')

p_area_rent = ggplot(data = hData_NF) +
  geom_boxplot(aes(x = rent, y = area, fill = locality), outlier.colour = "red") + 
  scale_fill_manual(values = pcustom_colors) +
  labs(x = "Rent", y = "Area", title = "Area by Rent and Locality for North facing") +
  facet_wrap(~ facing) +  # Add this line to create separate plots for west facing
  theme_minimal()

# Display the plot
p_area_rent
```

```{r}
hData_SF = hData %>% filter(facing == 'South')

p_area_rent = ggplot(data = hData_SF) +
  geom_boxplot(aes(x = rent, y = area, fill = locality), outlier.colour = "red") + 
  scale_fill_manual(values = pcustom_colors) +
  labs(x = "Rent", y = "Area", title = "Area by Rent and Locality for South facing") +
  facet_wrap(~ facing) +  # Add this line to create separate plots for west facing
  theme_minimal()

# Display the plot
p_area_rent
```

```{r}
hData_NWF = hData %>% filter(facing == 'North-West')

p_area_rent = ggplot(data = hData_NWF) +
  geom_boxplot(aes(x = rent, y = area, fill = locality), outlier.colour = "red") + 
  scale_fill_manual(values = pcustom_colors) +
  labs(x = "Rent", y = "Area", title = "Area by Rent and Locality for South facing") +
  facet_wrap(~ facing) +  # Add this line to create separate plots for west facing
  theme_minimal()

# Display the plot
p_area_rent
```

```{r}
hData_NEF = hData %>% filter(facing == 'North-East')

p_area_rent = ggplot(data = hData_NEF) +
  geom_boxplot(aes(x = rent, y = area, fill = locality), outlier.colour = "red") + 
  scale_fill_manual(values = pcustom_colors) +
  labs(x = "Rent", y = "Area", title = "Area by Rent and Locality for South facing") +
  facet_wrap(~ facing) +  # Add this line to create separate plots for west facing
  theme_minimal()

# Display the plot
p_area_rent
```

```{r}
hData_SEF = hData %>% filter(facing == 'South-East')

p_area_rent = ggplot(data = hData_SEF) +
  geom_boxplot(aes(x = rent, y = area, fill = locality), outlier.colour = "red") + 
  scale_fill_manual(values = pcustom_colors) +
  labs(x = "Rent", y = "Area", title = "Area by Rent and Locality for South facing") +
  facet_wrap(~ facing) +  # Add this line to create separate plots for west facing
  theme_minimal()

# Display the plot
p_area_rent
```

```{r}
distinct_values = unique(hData$facing)
print(distinct_values)
```

```{r}
p_area_rent = ggplot(data = hData) +
  geom_boxplot(aes(x = rent, y = area, fill = locality), outlier.colour = "red") + 
  scale_fill_manual(values = pcustom_colors) +
  labs(x = "Rent", y = "Area", title = "Area by Rent and Locality for BHK") +
  facet_wrap(~ BHK) +  # Add this line to create separate plots for each facing
  theme_minimal()

# Display the plot
p_area_rent
```

```{r}
hData_1BHK = hData %>% filter(BHK == 1)

p_area_rent = ggplot(data = hData_1BHK) +
  geom_boxplot(aes(x = rent, y = area, fill = locality), outlier.colour = "red") + 
  scale_fill_manual(values = pcustom_colors) +
  labs(x = "Rent", y = "Area", title = "Area by Rent and Locality for 1 BHK") +
  facet_wrap(~ BHK) +  # Assuming you have a column 'facing'
  theme_minimal()

# Display the plot
p_area_rent
```

```{r}
hData_2BHK = hData %>% filter(BHK == 2)

# Create the plot for 2 BHK
p_area_rent = ggplot(data = hData_2BHK) +
  geom_boxplot(aes(x = rent, y = area, fill = locality), outlier.colour = "red") + 
  scale_fill_manual(values = pcustom_colors) +
  labs(x = "Rent", y = "Area", title = "Area by Rent and Locality for 2 BHK") +
  facet_wrap(~ BHK) +  # Assuming you have a column 'facing'
  theme_minimal()

# Display the plot
p_area_rent
```

```{r}
hData_3BHK = hData %>% filter(BHK == 3)

# Create the plot for 2 BHK
p_area_rent = ggplot(data = hData_3BHK) +
  geom_boxplot(aes(x = rent, y = area, fill = locality), outlier.colour = "red") + 
  scale_fill_manual(values = pcustom_colors) +
  labs(x = "Rent", y = "Area", title = "Area by Rent and Locality for 3 BHK") +
  facet_wrap(~ BHK) +  # Assuming you have a column 'facing'
  theme_minimal()

# Display the plot
p_area_rent
```

```{r}
hData_4BHK = hData %>% filter(BHK == 4)

# Create the plot for 2 BHK
p_area_rent = ggplot(data = hData_4BHK) +
  geom_boxplot(aes(x = rent, y = area, fill = locality), outlier.colour = "red") + 
  scale_fill_manual(values = pcustom_colors) +
  labs(x = "Rent", y = "Area", title = "Area by Rent and Locality for 4 BHK") +
  facet_wrap(~ BHK) +  # Assuming you have a column 'facing'
  theme_minimal()

# Display the plot
p_area_rent
```


```{r}
p = ggplot(data = hData) +
  geom_bar(aes(x = BHK, fill = locality)) + scale_fill_manual(values = pcustom_colors) +
  labs(x = "BHK", y = "Count", title = "Count of House BHK by Locality")
p
```

```{r}
p_area_rent = ggplot(data = hData) +
  geom_boxplot(aes(x = rent, y = area, fill = locality), outlier.colour = "red") + 
  scale_fill_manual(values = pcustom_colors) +
  labs(x = "Rent", y = "Area", title = "Area by Rent and Locality for praking space") +
  facet_wrap(~parking) +  # Add this line to create separate plots for each facing
  theme_minimal()

# Display the plot
p_area_rent
```

```{r}
hData_Bike = hData %>% filter(parking == 'Bike')

p_area_rent = ggplot(data = hData_Bike) +
  geom_boxplot(aes(x = rent, y = area, fill = locality), outlier.colour = "red") + 
  scale_fill_manual(values = pcustom_colors) +
  labs(x = "Rent", y = "Area", title = "Area by Rent and Locality for praking space") +
  facet_wrap(~parking) +  # Add this line to create separate plots for each facing
  theme_minimal()

# Display the plot
p_area_rent
```

```{r}
hData_Bikecar = hData %>% filter(parking == 'Bike and Car')

p_area_rent = ggplot(data = hData_Bikecar) +
  geom_boxplot(aes(x = rent, y = area, fill = locality), outlier.colour = "red") + 
  scale_fill_manual(values = pcustom_colors) +
  labs(x = "Rent", y = "Area", title = "Area by Rent and Locality for praking space") +
  facet_wrap(~parking) +  # Add this line to create separate plots for each facing
  theme_minimal()

# Display the plot
p_area_rent
```

```{r}
hData_car = hData %>% filter(parking == 'Car')

p_area_rent = ggplot(data = hData_car) +
  geom_boxplot(aes(x = rent, y = area, fill = locality), outlier.colour = "red") + 
  scale_fill_manual(values = pcustom_colors) +
  labs(x = "Rent", y = "Area", title = "Area by Rent and Locality for praking space") +
  facet_wrap(~parking) +  # Add this line to create separate plots for each facing
  theme_minimal()

# Display the plot
p_area_rent
```

```{r}
p_area_rent = ggplot(data = hData) +
  geom_boxplot(aes(x = rent, y = area, fill = locality), outlier.colour = "red") + 
  scale_fill_manual(values = pcustom_colors) +
  labs(x = "Rent", y = "Area", title = "Area by Rent and Locality for bathrooms") +
  facet_wrap(~bathrooms) +  # Add this line to create separate plots for each facing
  theme_minimal()

# Display the plot
p_area_rent
```

```{r}
#One line of conculsion is that it is better to be in a rented house in the bangalore city given according to this dataset and it is seen that the prices vary a liitle from area to area and most of the houses fall in the range of 2000 sqrt and in the price range below 1,00,000 Rs and only in the area Jayanagar we can see that the price of the houses are above 1,00,000 and we have visiualsed the house and its renting facilites.
```

