---
title: "Assignment 3"
output: html_document
date: "2024-09-27"
---
```{r}
#Sampling space for appointment success (0 corresponds to no sale, 1 corresponds to a sale) 
s_appointment = c(0,1)
```

```{r}
#Appointment success and failure probabilities
p_morning = c(0.3) # Success probability of sales in morning
p_afternoon = c(0.6) # Success probability of sales in afternoon
p_appointment = matrix(nrow = 2, ncol = 2, c(1-p_morning, p_morning, 1-p_afternoon, p_afternoon), byrow = TRUE)
p_appointment
```
```{r}
#Sampling space for software type
s_software = c(5000, 10000)
```

```{r}
#Software type probabilities
p_software = matrix(nrow = 2, ncol = 2, c(0.3,0.7,0.5,0.5), byrow = TRUE)
p_software
```
```{r}
#Function that simulates one trial of the random experiment which is
#what the salesman earns on a random day
salesResult = function() {
  result = numeric(2)
  
  # Simulate whether sales happen in morning and afternoon appointments
  for (j in c(1:2)) {
    result[j] = sample(s_appointment, size = 1, replace = TRUE, prob = p_appointment[j, ])
  }
  
  # Calculate earnings based on morning and afternoon sales
  earnings = ifelse(result[1] == 1, sample(s_software, size = 1, replace = TRUE, prob = p_software[1, ]), 0) +
             ifelse(result[2] == 1, sample(s_software, size = 1, replace = TRUE, prob = p_software[2, ]), 0)
  
  return(earnings)
}
```

```{r}
#Number of simulations
nsimulations = 1e5
simulatedData = replicate(nsimulations, salesResult())
mean(simulatedData)
```

```{r}
#Probability that the salesman earns Rs 5000
mean(simulatedData == 0)
mean(simulatedData == 5000)
mean(simulatedData == 10000)
mean(simulatedData == 15000)
mean(simulatedData == 20000)
```

