---
title: "Linear Regression Coding Assignment-1"
editor_options:
  chunk_output_type: console
output: html_notebook
---
```{r}
install.packages("HSAUR")
install.packages("ggcorrplot")
```


```{r}
# Load essential libraries
library(ggplot2)
library(dplyr)
library(HSAUR)
library(ggcorrplot)
```

```{r}
# Load the heptathlon dataset
data(heptathlon)
str(heptathlon)
```


```{r}
data1 = read.csv()
```

```{r}
# Set ggplot theme for plotting
My_Theme = theme(axis.text.x = element_text(size = 9),
   axis.text.y = element_text(size = 9),
   axis.title.x = element_text(size = 11),
   axis.title.y = element_text(size = 11),
   plot.title = element_text(size = 12, hjust = 0.5, face = "bold"))
```

```{r}
# Introduce a new column called sprint highlighting slow and fast sprinters using the 25th percentile of run times in 200m and 800m
heptathlon = heptathlon %>% mutate(sprint = ifelse(run200m <= quantile(heptathlon$run200m, 0.25) & run800m <= quantile(heptathlon$run800m, 0.25), 'fast', 'slow'))
```

```{r}
# Change sprint column to factor type
heptathlon['sprint'] = lapply(heptathlon['sprint'],as.factor)
str(heptathlon)
```

```{r}
# How many levels does the categorical variable *sprint* have? What is the reference level? 
contrasts(heptathlon$sprint)
```

```{r}
# Create lists of categorical and continuous columns
categorical_cols = c('sprint')
continuous_cols = setdiff(colnames(heptathlon), categorical_cols)
```

```{r}
# Fit a linear model for approximating *score* as a function of *sprint*. Print the model's summary. How accurate is the model? How do the slow athletes' scores compare to the fast ones?
model1 = lm(data = heptathlon, score ~ sprint)
summary(model1)
```

```{r}
# Fit a linear model for approximating *score* as a function of *shot* and *sprint*. Print the model's summary and answer the following questions:

# 1. Did the addition of the new predictor *shot* improve the model accuracy? 
# 2. *True/false* (explain in one line): the model suggests that there is a possible linear relationship between an athlete's score and sprintslow.
# 3. For a 1 metre increase in shot put throw and with the same sprint performance, we can say with 95% confidence that the athlete's score will increase/decrease by an amount in the interval [?, ?].
model2 = lm(data = heptathlon, score ~ shot + sprint)
summary(model2)
```

```{r}
# Residual Sum of Squares (RSS) for Model 1
rss_model1 <- sum(residuals(model1)^2)
 
# Total Sum of Squares (TSS) for Model 1
tss_model1 <- sum((heptathlon$score - mean(heptathlon$score))^2)
 
# Print RSS and TSS for Model 1
cat("Model 1:\n")
cat("RSS:", rss_model1, "\n")
cat("TSS:", tss_model1, "\n\n")
cat("Res:", (tss_model1 - rss_model1)/tss_model1)
```

```{r}
# Residual Sum of Squares (RSS) for Model 2
rss_model2 <- sum(residuals(model2)^2)
 
# Total Sum of Squares (TSS) for Model 2
tss_model2 <- sum((heptathlon$score - mean(heptathlon$score))^2)
 
# Print RSS and TSS for Model 2
cat("Model 2:\n")
cat("RSS:", rss_model2, "\n")
cat("TSS:", tss_model2, "\n")
cat("Res:", (tss_model2 - rss_model2)/tss_model2)
```


```{r}
#  Using the model built above, extract the slope and intercept for estimating the *score* of *slow* and *fast* athletes. 
intercept_slow = ?
slope_slow = ?
intercept_fast = ?
slope_fast = ?
```

```{r}
# Fit a linear model for approximating *score* as a function of *shot*, *sprint*, and *javelin*. Print the model's summary.

# 1. Did the addition of the new predictor *javelin* improve the model accuracy?
# 2. *True/false* (explain in one line): the model suggests that there is a possible linear relationship between an athlete's score and javelin performance.
# 3. For a 1 metre increase in shot put throw and with the same javelin and sprint performance, we can say with 95% confidence that the athlete's score will increase/decrease by an amount in the interval [?, ?].
?
```

```{r}
# Fit a linear model for approximating score as a function of highjump, and sprint. Print the model's summary and answer the following questions:

# 1. How accurate is this model?
# 2. Considering a p-value of 10% as cutoff, are there any insignificant features?
# 3. extract the slope and intercept for estimating the *score* of *slow* and *fast* athletes.
?
```

```{r}
# Fit a linear model for approximating *score* as a function of *shot*, *highjump*, and *sprint*. Print the model's summary and answer the following questions:

# 1. How accurate is this model?
# 2. Considering a p-value of 10% as cutoff, are there any insignificant features?
?
```

```{r}
# Predict the model out-of-sample performance by applying it to the test data.
# Split the data into 80% train and 20% test parts
set.seed(0)
train_ind = sample(seq_len(nrow(hData)), size = floor(0.8 * nrow(hData)))

hDataTrain = ?
hDataTest = ?

# Build linear regression model


# Predict on the test data


# Print the true scores for the test data

```



